services:
  evently.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/Evently.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${EVENTLY_HTTPS_CERT_PASSWORD}
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro