services:
  evently.api:
    image: eventlyapi
    container_name: Evently.Api
    build:
      context: .
      dockerfile: src/API/Evently.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  evently.database:
    image: postgres:latest
    container_name: Evently.Database
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postresql/data
    ports:
      - "5432:5432"
  
  evently.idendity:
    image: quay.io/keycloak/keycloak:latest
    container_name: Evently.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - "18080:8080"
      - "9000:9000" #on newer version of keycloak, health endpoint is expose in port 9000 by default

  evently.seq:
    image: datalust/seq:latest
    container_name: Evently.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=GoodPassword67
    ports:
      - "5431:5431"
      - "8081:80"
  
  evently.redis:
    image: redis:latest
    container_name: Evently.Redis
    restart: always
    ports:
      - "6379:6379"